AWSTemplateFormatVersion: '2010-09-09'
Description: Simple 3-Tier Architecture with 1 Public EC2, 1 Private RDS, and 1 S3 Bucket.

# --- PARAMETERS SECTION ---
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access.
    Default: MyKeyPair
    AllowedPattern: "[a-zA-Z0-9-]+"
  
  EnvironmentType:
    Type: String
    Description: Environment for this stack (dev or prod).
    Default: dev
    AllowedValues:
      - dev
      - prod
      
  DBName:
    Type: String
    Description: The name of the database to create.
    Default: testdb
    MinLength: 1

  DBUser:
    Type: String
    Description: Master username for the RDS database.
    Default: dbmaster
    MinLength: 1

  DBPassword:
    Type: String
    Description: Master password for the RDS database.
    NoEcho: true
    Default: MySecurePass123!
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9!@#%^&*]+"


# --- RESOURCES SECTION ---
Resources:

  # 1. Networking Foundation (VPC, IGW, Routing)
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-IGW

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # 2. Subnets (One Public, One Private)
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PrivateSubnet

  # 3. Public Routing
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PublicRT

  PublicInternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # 4. Security Groups
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH (22) and HTTP (80) to Web Server
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2-SG

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL traffic only from the EC2 Web Server
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-DB-SG

  # 5. EC2 Instance (Compute)
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00e15f0027b9bf02b # Amazon Linux 2023
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub MyInstance-${EnvironmentType} # Required tag pattern
        - Key: Environment
          Value: !Ref EnvironmentType
      UserData:
        !Base64
        Fn::Sub: |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>CloudFormation Test Task - Web Server</h1>" > /var/www/html/index.html

  # 6. RDS Database (Data Tier)
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS instance
      SubnetIds:
        - !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDS-SubnetGroup

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName # Uses Parameter
      Engine: mysql
      MasterUsername: !Ref DBUser # Uses Parameter
      MasterUserPassword: !Ref DBPassword # Uses Parameter
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      MultiAZ: 'false' # Simplified to single AZ for test
      PubliclyAccessible: 'false'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-MySQL-DB
        - Key: Environment
          Value: !Ref EnvironmentType

  # 7. S3 Bucket (Storage Tier)
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-s3-bucket"
      VersioningConfiguration:
        Status: Suspended # Simple default for testing
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-s3-bucket
        - Key: Environment
          Value: !Ref EnvironmentType

# --- OUTPUTS SECTION ---
Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !Ref VPC

  EC2InstanceId:
    Description: The ID of the EC2 Instance
    Value: !Ref EC2Instance

  EC2PublicIP:
    Description: The Public IP Address of the Web Server
    Value: !GetAtt EC2Instance.PublicIp

  S3BucketName:
    Description: The name of the S3 Storage Bucket
    Value: !Ref S3Bucket